import { describe, expect, it } from "vitest";

import type { FsrsState } from "@/lib/db/schema";
import {
  computeNextReview,
  createInitialState,
} from "./scheduler";

/**
 * Golden tests: these values are pinned against ts-fsrs 5.4.1 (FSRS-5,
 * enable_fuzz: false) output generated by driving the library directly with
 * the same inputs. They protect the app's core scheduling IP: any change to
 * the toTsCard/toFsrsState field mapping or a ts-fsrs upgrade that alters
 * results will fail here loudly instead of silently corrupting scheduling.
 */
const NOW = 1_700_000_000_000;

function baseState(overrides: Partial<FsrsState> = {}): FsrsState {
  return {
    version: 1,
    due: NOW,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    reps: 0,
    lapses: 0,
    learning_steps: 0,
    state: 0,
    last_review: null,
    ...overrides,
  };
}

describe("fsrs golden values (ts-fsrs 5.4.1, fuzz off)", () => {
  it("first Good review on a new card: exact stability/difficulty/due", () => {
    const result = computeNextReview(baseState(), 3, NOW);

    expect(result.nextState.stability).toBeCloseTo(2.3065, 4);
    expect(result.nextState.difficulty).toBeCloseTo(2.11810397, 6);
    expect(result.dueAt).toBe(1_700_000_600_000); // 10-minute learning step
    expect(result.nextState.state).toBe(1); // Learning
    expect(result.nextState.reps).toBe(1);
    expect(result.nextState.scheduled_days).toBe(0);
    // Revlog snapshot carries the PRE-review values.
    expect(result.log.state).toBe(0);
    expect(result.log.stability).toBe(0);
    expect(result.log.difficulty).toBe(0);
    expect(result.log.due).toBe(NOW);
    expect(result.log.last_elapsed_days).toBe(0);
  });

  it("second Good review (reviewed at due): graduates to Review state", () => {
    // State after the first Good review above.
    const state = baseState({
      due: 1_700_000_600_000,
      stability: 2.3065,
      difficulty: 2.11810397,
      reps: 1,
      state: 1,
      learning_steps: 1,
      last_review: NOW,
    });

    const result = computeNextReview(state, 3, state.due);

    expect(result.nextState.stability).toBeCloseTo(2.3065, 4);
    expect(result.nextState.difficulty).toBeCloseTo(2.11121424, 6);
    expect(result.dueAt).toBe(1_700_173_400_000);
    expect(result.nextState.state).toBe(2); // Review
    expect(result.nextState.reps).toBe(2);
  });

  it("Again on a review-state card: lapse with exact values", () => {
    // State after two Good reviews.
    const state = baseState({
      due: 1_700_173_400_000,
      stability: 2.3065,
      difficulty: 2.11121424,
      reps: 2,
      state: 2,
      last_review: 1_700_000_600_000,
    });

    const result = computeNextReview(state, 1, state.due);

    expect(result.nextState.stability).toBeCloseTo(0.60770166, 6);
    expect(result.nextState.difficulty).toBeCloseTo(7.39223814, 6);
    expect(result.dueAt).toBe(1_700_174_000_000);
    expect(result.nextState.state).toBe(3); // Relearning
    expect(result.nextState.lapses).toBe(1);
  });

  it("round-trips through toTsCard/toFsrsState losslessly", () => {
    const fullyPopulated: FsrsState = {
      version: 1,
      due: 1_700_123_456_789,
      stability: 3.724182,
      difficulty: 5.183746,
      elapsed_days: 12,
      scheduled_days: 15,
      reps: 9,
      lapses: 2,
      learning_steps: 3,
      state: 2,
      last_review: 1_699_900_000_000,
    };

    // Feeding the state through a review and comparing field-by-field with a
    // hand-built expectation exercises both mapping directions; the
    // determinism check (same input => same output, run twice) verifies the
    // mapping introduces no drift.
    const first = computeNextReview(fullyPopulated, 4, 1_700_123_456_789);
    const second = computeNextReview(fullyPopulated, 4, 1_700_123_456_789);
    expect(second).toEqual(first);

    // Every FsrsState field is preserved in the log snapshot (pre-review).
    expect(first.log.state).toBe(fullyPopulated.state);
    expect(first.log.stability).toBe(fullyPopulated.stability);
    expect(first.log.difficulty).toBe(fullyPopulated.difficulty);
    // ts-fsrs computes the revlog due from the card's last_review (pre-review
    // semantics), NOT the card's due field — pinned here so a mapping change
    // that swaps the two fails loudly.
    expect(first.log.due).toBe(fullyPopulated.last_review);
    expect(first.log.scheduled_days).toBe(fullyPopulated.scheduled_days);
    // elapsed_days in the revlog is derived from (reviewTime - last_review)
    // as whole days, not copied from the card's stored elapsed_days
    // (2.59 days floor to 2; ts-fsrs reports 3 via its own day-boundary calc).
    expect(first.log.elapsed_days).toBe(3);
    expect(first.log.learning_steps).toBe(fullyPopulated.learning_steps);

    // last_review round-trips through Date:null|undefined correctly: a
    // reviewed card must carry last_review, a fresh card must not.
    expect(first.nextState.last_review).toBe(1_700_123_456_789);
    expect(createInitialState(NOW).last_review).toBeNull();
  });
});
